# Taskfile for banner generator
# https://taskfile.dev/

version: '3'

tasks:
  default:
    desc: Generate banner
    deps: [install]
    cmds:
      - bun run generate.js

  generate:
    desc: Generate banner
    deps: [install]
    cmds:
      - bun run generate.js

  install:
    desc: Install dependencies
    cmds:
      - bun install
    sources:
      - package.json
    generates:
      - node_modules/.package-lock.json

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf node_modules tygor-banner.svg
